baseURL = 'http://sites.robigan.com/'
languageCode = 'en-us'
title = "Robigan's Sitelist"
theme = "lynx"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Robigan's Sitelist"
  headline = "A collection of sites I find useful and interesting that others may like"
  image = "pfp.png"
  links = [
    { link = { href = "https://robigan.com", text = "Homepage" } },
    { flightradar24 = "https://flightradar24.com" },
    { farside = "https://farside.link" },
    { bibliogram = "https://bibliogram.art" },
    { invidious ="https://invidious.snopyta.org" },
    { libreddit = "https://libredd.it" },
    { lingva = "https://lingva.ml" },
    { nitter = "https://nitter.it" },
    { proxitok = "https://proxitok.herokuapp.com" },
    { tempmail = "https://temp-mail.org" },
    { imagecolorpicker = "https://imagecolorpicker.com" },
    { convertio = "https://convertio.co" },
    { archivedotorg = "https://archive.org"},
    { autodraw = "https://autodraw.com" },
    { mastodon = "https://mastodon.social" },
    { keybase = "https://keybase.io" },
    { unscreen = "https://unscreen.com" },
    { removebg = "https://remove.bg" },
    { virustotal = "https://virustotal.com "},
    { justwatch = "https://justwatch.com" },
    { quillbot = "https://quillbot.com" },
    { twelvefootladder = "https://12ft.io" },
    { untools = "https://untools.co" },
    { otter = "https://otter.ai" },
    { darebee = "https://darebee.com" },
    { thenounproject = "https://thenounproject.com" },
    { openlibrary = "https://openlibrary.org" },
    { omnicalculator = "https://www.omnicalculator.com" },
    { manualsnet = "https://manualsnet.com" },
    { calligraphr = "https://calligraphr.com" },
    { wewave = "https://wewave.app" },
    { lumen5 = "https://lumen5.com" },
    { lordicon = "https://lordicon.com" }
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
